DELETE FROM books;
ALTER TABLE books ALTER COLUMN id RESTART WITH 1;

DELETE FROM authors;
ALTER TABLE authors ALTER COLUMN id RESTART WITH 1;

DELETE FROM genres;
ALTER TABLE genres ALTER COLUMN id RESTART WITH 1;